"""empty message

Revision ID: 2e678212abd6
Revises: f31c9658523c
Create Date: 2021-02-07 18:25:12.328128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e678212abd6'
down_revision = 'f31c9658523c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backstage_accounts', 'role_id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='角色id',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backstage_accounts', 'role_id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment=None,
               existing_comment='角色id',
               existing_nullable=False)
    # ### end Alembic commands ###
