"""empty message

Revision ID: 42468a92f183
Revises: 6df03070f225
Create Date: 2021-02-08 14:44:48.717073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42468a92f183'
down_revision = '6df03070f225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_api_permissions_endpoint'), 'api_permissions', ['endpoint'], unique=False)
    op.create_unique_constraint(None, 'api_permissions', ['endpoint', 'method'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_permissions', type_='unique')
    op.drop_index(op.f('ix_api_permissions_endpoint'), table_name='api_permissions')
    # ### end Alembic commands ###
