"""empty message

Revision ID: 4e25b8d0e4fe
Revises: 77e9c3c4743d
Create Date: 2021-02-08 14:27:39.069641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e25b8d0e4fe'
down_revision = '77e9c3c4743d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='backstage_permissions')
    op.drop_table('backstage_permissions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backstage_permissions',
    sa.Column('id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False, comment='权限名称'),
    sa.Column('desc', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False, comment='权限描述'),
    sa.Column('parent_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True, comment='父级权限'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='删除标志'),
    sa.CheckConstraint('(`is_delete` in (0,1))', name='backstage_permissions_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    comment='后台管理系统页面权限表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='后台管理系统页面权限表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'backstage_permissions', ['name'], unique=True)
    # ### end Alembic commands ###
