"""empty message

Revision ID: 5db203661a44
Revises: 42468a92f183
Create Date: 2021-02-08 14:57:05.172695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5db203661a44'
down_revision = '42468a92f183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_backstage_accounts_role_id'), 'backstage_accounts', ['role_id'], unique=False)
    op.alter_column('backstage_roles', 'permissions_set',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               type_=sa.String(length=500),
               existing_comment='权限id,以,分割',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backstage_roles', 'permissions_set',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               existing_comment='权限id,以,分割',
               existing_nullable=False)
    op.drop_index(op.f('ix_backstage_accounts_role_id'), table_name='backstage_accounts')
    # ### end Alembic commands ###
