"""empty message

Revision ID: 5f299af02a3e
Revises: f6e3d9f81ada
Create Date: 2021-02-08 14:38:44.387399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f299af02a3e'
down_revision = 'f6e3d9f81ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_permissions', sa.Column('method', sa.String(length=10), nullable=False, comment='请求方法'))
    op.drop_column('api_permissions', 'methods')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_permissions', sa.Column('methods', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False, comment='请求方法,'))
    op.drop_column('api_permissions', 'method')
    # ### end Alembic commands ###
