"""empty message

Revision ID: 77e9c3c4743d
Revises: 2e678212abd6
Create Date: 2021-02-08 14:21:27.618272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77e9c3c4743d'
down_revision = '2e678212abd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_permissions',
    sa.Column('id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('endpoint', sa.String(length=300), nullable=False, comment='endpoint'),
    sa.Column('methods', sa.String(length=50), nullable=False, comment='请求方法,'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='删除标志'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint'),
    comment='接口权限表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_permissions')
    # ### end Alembic commands ###
