"""empty message

Revision ID: 91f67599c814
Revises: 43eed2f166ca
Create Date: 2021-01-25 10:34:25.231276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91f67599c814'
down_revision = '43eed2f166ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('accounts', 'is_delete',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='删除标志',
               existing_server_default=sa.text("'0'"))
    op.alter_column('accounts', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('accounts', 'is_delete',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_comment='删除标志',
               existing_server_default=sa.text("'0'"))
    op.alter_column('accounts', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
