"""empty message

Revision ID: 9f03bd247fc5
Revises: 91f67599c814
Create Date: 2021-02-07 10:30:34.273828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f03bd247fc5'
down_revision = '91f67599c814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('login_at', sa.DateTime(), nullable=True, comment='登录时间'))
    op.add_column('accounts', sa.Column('login_expired_at', sa.DateTime(), nullable=True, comment='登录过期时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'login_expired_at')
    op.drop_column('accounts', 'login_at')
    # ### end Alembic commands ###
