"""empty message

Revision ID: a2750a892472
Revises: 85a44b08f2e5
Create Date: 2021-02-07 13:26:43.377127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2750a892472'
down_revision = '85a44b08f2e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backstage_accounts',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('account_id', mysql.BIGINT(unsigned=True), nullable=False, comment='统一账户'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色id'),
    sa.Column('is_staff', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否是平台方账号'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    comment='后台管理系统账户表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backstage_accounts')
    # ### end Alembic commands ###
