"""empty message

Revision ID: b450755ffc4b
Revises: a2750a892472
Create Date: 2021-02-07 14:03:15.178017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b450755ffc4b'
down_revision = 'a2750a892472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backstage_roles', sa.Column('desc', sa.String(length=100), nullable=False, comment='角色描述'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backstage_roles', 'desc')
    # ### end Alembic commands ###
