"""empty message

Revision ID: c70cd6316bd2
Revises: ce4ebc54ef71
Create Date: 2021-02-07 13:15:21.542512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c70cd6316bd2'
down_revision = 'ce4ebc54ef71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backstage_permissions',
    sa.Column('id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='权限名称'),
    sa.Column('desc', sa.String(length=100), nullable=False, comment='权限描述'),
    sa.Column('parent_id', mysql.SMALLINT(unsigned=True), nullable=True, comment='父级权限'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='删除标志'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='后台管理系统页面权限表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backstage_permissions')
    # ### end Alembic commands ###
