"""empty message

Revision ID: ce4ebc54ef71
Revises: 
Create Date: 2021-02-07 12:03:42.922281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce4ebc54ef71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='删除标志'),
    sa.Column('cellphone', sa.String(length=12), nullable=False, comment='手机号'),
    sa.Column('name', sa.String(length=50), server_default='', nullable=False, comment='姓名'),
    sa.Column('nickname', sa.String(length=50), server_default='', nullable=False, comment='昵称'),
    sa.Column('password_hash', sa.String(length=300), nullable=False, comment='密码加密'),
    sa.Column('login_at', sa.DateTime(), nullable=True, comment='登录时间'),
    sa.Column('login_expired_at', sa.DateTime(), nullable=True, comment='登录过期时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cellphone'),
    comment='账户表'
    )
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
