"""empty message

Revision ID: d20e7c0aa39d
Revises: f10f62000ad2
Create Date: 2021-02-08 14:30:31.970364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20e7c0aa39d'
down_revision = 'f10f62000ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_permissions', sa.Column('desc', sa.String(length=100), nullable=True, comment='描述简介'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_permissions', 'desc')
    # ### end Alembic commands ###
