"""empty message

Revision ID: f10f62000ad2
Revises: 4e25b8d0e4fe
Create Date: 2021-02-08 14:28:28.446352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f10f62000ad2'
down_revision = '4e25b8d0e4fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_permissions', sa.Column('name', sa.String(length=50), nullable=False, comment='权限名称'))
    op.add_column('api_permissions', sa.Column('parent_id', mysql.SMALLINT(unsigned=True), nullable=True, comment='父级权限'))
    op.create_unique_constraint(None, 'api_permissions', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_permissions', type_='unique')
    op.drop_column('api_permissions', 'parent_id')
    op.drop_column('api_permissions', 'name')
    # ### end Alembic commands ###
