"""empty message

Revision ID: f6e3d9f81ada
Revises: d20e7c0aa39d
Create Date: 2021-02-08 14:33:31.060248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6e3d9f81ada'
down_revision = 'd20e7c0aa39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_permissions', sa.Column('url', sa.String(length=200), nullable=True, comment='页面url'))
    op.alter_column('api_permissions', 'endpoint',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=300),
               nullable=True,
               existing_comment='endpoint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_permissions', 'endpoint',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=300),
               nullable=False,
               existing_comment='endpoint')
    op.drop_column('api_permissions', 'url')
    # ### end Alembic commands ###
